import type { InventoryItem, Category } from "../types";

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Electronics" },
  { id: "cat-2", name: "Office Supplies" },
  { id: "cat-3", name: "Furniture" },
  { id: "cat-4", name: "Janitorial" },
  { id: "cat-5", name: "Networking" },
];

export const mockItems: InventoryItem[] = [
  {
    id: "item-1",
    name: "MacBook Pro M3",
    sku: "LAP-MP-M3",
    category_id: "cat-1",
    quantity: 12,
    reorder_threshold: 5,
    supplier: "Apple Inc.",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-2",
    name: "Dell UltraSharp 27",
    sku: "MON-DELL-27",
    category_id: "cat-1",
    quantity: 3,
    reorder_threshold: 10,
    supplier: "Dell Technologies",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-3",
    name: "Logitech MX Master 3S",
    sku: "PER-LOG-MX3S",
    category_id: "cat-1",
    quantity: 45,
    reorder_threshold: 15,
    supplier: "Logitech",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-4",
    name: "A4 Printer Paper (Ream)",
    sku: "OFF-PAP-A4",
    category_id: "cat-2",
    quantity: 120,
    reorder_threshold: 50,
    supplier: "Staples",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-5",
    name: "Gel Pens (Box of 12)",
    sku: "OFF-PEN-GEL",
    category_id: "cat-2",
    quantity: 8,
    reorder_threshold: 20,
    supplier: "Staples",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-6",
    name: "Ergonomic Mesh Chair",
    sku: "FUR-CHR-ERG",
    category_id: "cat-3",
    quantity: 15,
    reorder_threshold: 5,
    supplier: "Herman Miller",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-7",
    name: "Standing Desk 60-inch",
    sku: "FUR-DSK-60",
    category_id: "cat-3",
    quantity: 2,
    reorder_threshold: 5,
    supplier: "Uplift Desk",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-8",
    name: "Multi-Surface Cleaner",
    sku: "JAN-CLN-MS",
    category_id: "cat-4",
    quantity: 34,
    reorder_threshold: 15,
    supplier: "Clorox",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-9",
    name: "Trash Bags 13 Gal (Box)",
    sku: "JAN-BAG-13G",
    category_id: "cat-4",
    quantity: 60,
    reorder_threshold: 20,
    supplier: "Glad",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-10",
    name: "Cat6 Ethernet Cable (10ft)",
    sku: "NET-CBL-C6-10",
    category_id: "cat-5",
    quantity: 85,
    reorder_threshold: 30,
    supplier: "Cable Matters",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-11",
    name: "Unifi Pro Access Point",
    sku: "NET-WAP-PRO",
    category_id: "cat-5",
    quantity: 4,
    reorder_threshold: 10,
    supplier: "Ubiquiti",
    created_at: new Date().toISOString(),
  },
  {
    id: "item-12",
    name: "24-Port Gigabit Switch",
    sku: "NET-SWT-24G",
    category_id: "cat-5",
    quantity: 7,
    reorder_threshold: 5,
    supplier: "Ubiquiti",
    created_at: new Date().toISOString(),
  },
];
